name: Manual Run Main.py

on:
  workflow_dispatch:
    inputs:
      script-name:
        description: 'Name of the script to run'
        required: true
        default: 'main.py'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Run Script
        run: python ${{ inputs.script-name }}
