name: Manual Run robertmcdaniel7100.py

on:
  workflow_dispatch:
    inputs:
      script-name:
        description: 'Name of the script to run'
        required: true
        default: 'robertmcdaniel7100.py'

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: pip install -r requirements.txt  # Add this if you have a requirements.txt file
      
      - name: Run Script
        run: python ${{ inputs.script-name }}
